# Generated by Django 5.1.4 on 2025-02-05 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=255, unique=True)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=18, max_digits=30)),
                ('timestamp', models.DateTimeField()),
                ('chain', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['from_address'], name='analysis_tr_from_ad_23d9ea_idx'), models.Index(fields=['to_address'], name='analysis_tr_to_addr_c6638b_idx'), models.Index(fields=['timestamp'], name='analysis_tr_timesta_66e33a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('connection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('connection_type', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['wallet_address'], name='analysis_wa_wallet__ea30a7_idx'), models.Index(fields=['ip_address'], name='analysis_wa_ip_addr_b39875_idx'), models.Index(fields=['connection_time'], name='analysis_wa_connect_42f5fc_idx')],
            },
        ),
    ]
